package com.example.ocean.Utils

object Constants {
    const val DEFAULT_INPUT_COUNTRY = "English"
    const val DEFAULT_OUTPUT_COUNTRY = "Vietnamese"
    val supportedLanguageList = listOf(
        CountryLanguage("ZA", "Afrikaans"),
        CountryLanguage("AL", "Albanian"),
        CountryLanguage("ET", "Amharic"),
        CountryLanguage("SA", "Arabic"),
        CountryLanguage("AM", "Armenian"),
        CountryLanguage("AZ", "Azerbaijani"),
        CountryLanguage("ES", "Basque"),
        CountryLanguage("BY", "Belarusian"),
        CountryLanguage("BD", "Bengali"),
        CountryLanguage("BA", "Bosnian"),
        CountryLanguage("BG", "Bulgarian"),
        CountryLanguage("ES", "Catalan"),
        CountryLanguage("PH", "Cebuano"),
        CountryLanguage("MW", "Chichewa"),
        CountryLanguage("CN", "Chinese (Simplified)"),
        CountryLanguage("TW", "Chinese (Traditional)"),
        CountryLanguage("FR", "Corsican"),
        CountryLanguage("HR", "Croatian"),
        CountryLanguage("CZ", "Czech"),
        CountryLanguage("DK", "Danish"),
        CountryLanguage("NL", "Dutch"),
        CountryLanguage("US", "English"),
        CountryLanguage("EO", "Esperanto"),
        CountryLanguage("EE", "Estonian"),
        CountryLanguage("PH", "Filipino"),
        CountryLanguage("FI", "Finnish"),
        CountryLanguage("FR", "French"),
        CountryLanguage("NL", "Frisian"),
        CountryLanguage("ES", "Galician"),
        CountryLanguage("GE", "Georgian"),
        CountryLanguage("DE", "German"),
        CountryLanguage("GR", "Greek"),
        CountryLanguage("IN", "Gujarati"),
        CountryLanguage("HT", "Haitian Creole"),
        CountryLanguage("NG", "Hausa"),
        CountryLanguage("US", "Hawaiian"),
        CountryLanguage("IL", "Hebrew"),
        CountryLanguage("IN", "Hindi"),
        CountryLanguage("CN", "Hmong"),
        CountryLanguage("HU", "Hungarian"),
        CountryLanguage("IS", "Icelandic"),
        CountryLanguage("NG", "Igbo"),
        CountryLanguage("ID", "Indonesian"),
        CountryLanguage("IE", "Irish"),
        CountryLanguage("IT", "Italian"),
        CountryLanguage("JP", "Japanese"),
        CountryLanguage("ID", "Javanese"),
        CountryLanguage("IN", "Kannada"),
        CountryLanguage("KZ", "Kazakh"),
        CountryLanguage("KH", "Khmer"),
        CountryLanguage("RW", "Kinyarwanda"),
        CountryLanguage("KR", "Korean"),
        CountryLanguage("IQ", "Kurdish (Kurmanji)"),
        CountryLanguage("KG", "Kyrgyz"),
        CountryLanguage("LA", "Lao"),
        CountryLanguage("VA", "Latin"),
        CountryLanguage("LV", "Latvian"),
        CountryLanguage("LT", "Lithuanian"),
        CountryLanguage("LU", "Luxembourgish"),
        CountryLanguage("MK", "Macedonian"),
        CountryLanguage("MG", "Malagasy"),
        CountryLanguage("MY", "Malay"),
        CountryLanguage("IN", "Malayalam"),
        CountryLanguage("MT", "Maltese"),
        CountryLanguage("NZ", "Maori"),
        CountryLanguage("IN", "Marathi"),
        CountryLanguage("MN", "Mongolian"),
        CountryLanguage("MM", "Myanmar (Burmese)"),
        CountryLanguage("NP", "Nepali"),
        CountryLanguage("NO", "Norwegian"),
        CountryLanguage("IN", "Odia (Oriya)"),
        CountryLanguage("AF", "Pashto"),
        CountryLanguage("IR", "Persian"),
        CountryLanguage("PL", "Polish"),
        CountryLanguage("PT", "Portuguese"),
        CountryLanguage("BR", "Portuguese"),
        CountryLanguage("IN", "Punjabi"),
        CountryLanguage("RO", "Romanian"),
        CountryLanguage("RU", "Russian"),
        CountryLanguage("WS", "Samoan"),
        CountryLanguage("GB", "Scots Gaelic"),
        CountryLanguage("RS", "Serbian"),
        CountryLanguage("LS", "Sesotho"),
        CountryLanguage("ZW", "Shona"),
        CountryLanguage("PK", "Sindhi"),
        CountryLanguage("LK", "Sinhala"),
        CountryLanguage("SK", "Slovak"),
        CountryLanguage("SI", "Slovenian"),
        CountryLanguage("SO", "Somali"),
        CountryLanguage("ES", "Spanish"),
        CountryLanguage("ID", "Sundanese"),
        CountryLanguage("KE", "Swahili"),
        CountryLanguage("SE", "Swedish"),
        CountryLanguage("TJ", "Tajik"),
        CountryLanguage("IN", "Tamil"),
        CountryLanguage("RU", "Tatar"),
        CountryLanguage("IN", "Telugu"),
        CountryLanguage("TH", "Thai"),
        CountryLanguage("TR", "Turkish"),
        CountryLanguage("TM", "Turkmen"),
        CountryLanguage("UA", "Ukrainian"),
        CountryLanguage("PK", "Urdu"),
        CountryLanguage("CN", "Uyghur"),
        CountryLanguage("UZ", "Uzbek"),
        CountryLanguage("VN", "Vietnamese"),
        CountryLanguage("GB", "Welsh"),
        CountryLanguage("ZA", "Xhosa"),
        CountryLanguage("IL", "Yiddish"),
        CountryLanguage("NG", "Yoruba"),
        CountryLanguage("ZA", "Zulu")
    )
}